import { Routes } from '@angular/router';
import { NewChat } from './new-chat/new-chat';
import { Chat } from './chat/chat';

export const routes: Routes = [
  {
    path: '',
    component: NewChat,
    title: 'Welcome to support chart'
  },
  {
    path: 'chat/:id',
    component: Chat,
    title: '' // Autogenerated for each session
  }
];
